package in.turls.lib.constants;

public enum ApiRequestErrorCode {

	INTERNAL_SERVER_ERROR, INVALID_SHORT_URL_ID, URL_NOT_FOUND, API_CALL_LIMIT_REACHED, INVALID_URL_SCHEME,
	INVALID_URL_EXPIRY_UNIT, INVALID_URL_EXPIRY_VALUE, INVALID_URL_LENGTH
}
